import React, { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import { CheckCircle2, Circle, Clock, BookOpen, ChevronDown, ChevronUp, Sparkles, Map, Calendar, ExternalLink } from 'lucide-react';
import { api } from '../../services/api';
import { useAuth } from '../../context/AuthContext';

export const InteractiveRoadmap: React.FC = () => {
  const [searchParams] = useSearchParams();
  const careerId = searchParams.get('careerId') || 'fullstack-engineer';

  const { updateUserSkill } = useAuth();
  const [roadmapData, setRoadmapData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [openStages, setOpenStages] = useState<{ [key: number]: boolean }>({ 1: true, 2: true });

  const fetchRoadmap = async () => {
    try {
      setLoading(true);
      const res = await api.get(`/roadmap?careerId=${careerId}`);
      if (res.data.success) {
        setRoadmapData(res.data);
      }
    } catch (err) {
      console.warn('Roadmap fallback');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRoadmap();
  }, [careerId]);

  const toggleStage = (stageNum: number) => {
    setOpenStages(prev => ({ ...prev, [stageNum]: !prev[stageNum] }));
  };

  const handleToggleSkillComplete = async (skillId: string, currentCompleted: boolean) => {
    const nextProf = currentCompleted ? 1 : 5;
    const nextStatus = currentCompleted ? 'Learning' : 'Completed';
    await updateUserSkill(skillId, nextProf, nextStatus);
    fetchRoadmap();
  };

  if (loading) {
    return (
      <div className="p-12 text-center text-xs font-mono text-slate-500 animate-pulse">
        Generating Topological Stage Sequences & Interactive Learning Roadmap...
      </div>
    );
  }

  const roadmap = roadmapData?.roadmap;
  const career = roadmapData?.career;

  return (
    <div className="p-6 lg:p-10 max-w-6xl mx-auto space-y-8 animate-in fade-in duration-300">
      {/* Header Banner */}
      <div className="glass-panel border border-slate-800 rounded-3xl p-8 flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
        <div className="space-y-2">
          <div className="flex items-center gap-2">
            <span className="text-xs font-mono px-3 py-1 rounded-full bg-indigo-500/20 text-indigo-300 border border-indigo-500/30 font-semibold">
              Interactive Roadmap
            </span>
            <span className="text-xs font-mono px-3 py-1 rounded-full bg-slate-800 text-slate-300">
              {career?.title}
            </span>
          </div>
          <h1 className="text-3xl font-extrabold text-white">Your Personalized Learning Path</h1>
          <p className="text-xs text-slate-400">
            Topologically ordered sequence generated by NEXUS Skill Knowledge Graph Engine.
          </p>
        </div>

        {/* Total Stats Box */}
        <div className="bg-slate-900/90 border border-slate-800 p-4 rounded-2xl flex items-center gap-6 text-xs font-mono">
          <div>
            <span className="text-slate-500 block text-[10px] uppercase">Progress</span>
            <span className="text-xl font-bold text-emerald-400">{roadmap?.progressPercentage}%</span>
          </div>
          <div className="border-l border-slate-800 pl-6">
            <span className="text-slate-500 block text-[10px] uppercase">Remaining Time</span>
            <span className="text-xl font-bold text-white flex items-center gap-1">
              <Clock className="w-4 h-4 text-indigo-400" /> {roadmap?.remainingHours}h (~{roadmap?.estimatedWeeksLeft} wks)
            </span>
          </div>
        </div>
      </div>

      {/* Progress Bar */}
      <div className="w-full bg-slate-900 border border-slate-800 h-3 rounded-full overflow-hidden p-0.5">
        <div
          className="bg-gradient-to-r from-indigo-500 via-cyan-400 to-emerald-400 h-full rounded-full transition-all duration-500"
          style={{ width: `${roadmap?.progressPercentage}%` }}
        />
      </div>

      {/* Roadmap Stages */}
      <div className="space-y-6">
        {roadmap?.stages?.map((stage: any) => {
          const isOpen = openStages[stage.stageNumber];
          return (
            <div key={stage.stageNumber} className="glass-panel border border-slate-800 rounded-3xl overflow-hidden transition-all">
              {/* Stage Header */}
              <div
                onClick={() => toggleStage(stage.stageNumber)}
                className="p-5 bg-slate-900/60 hover:bg-slate-900 cursor-pointer flex items-center justify-between transition-colors"
              >
                <div className="flex items-center gap-4">
                  <div className="w-10 h-10 rounded-2xl bg-indigo-600/20 text-indigo-400 font-bold flex items-center justify-center border border-indigo-500/30">
                    {stage.stageNumber}
                  </div>
                  <div>
                    <h3 className="text-base font-bold text-white">{stage.title}</h3>
                    <p className="text-xs text-slate-400 mt-0.5">{stage.description}</p>
                  </div>
                </div>

                <div className="flex items-center gap-4">
                  <span className="text-xs font-mono text-slate-400">
                    {stage.completedCount} / {stage.totalCount} Done
                  </span>
                  {isOpen ? <ChevronUp className="w-5 h-5 text-slate-400" /> : <ChevronDown className="w-5 h-5 text-slate-400" />}
                </div>
              </div>

              {/* Stage Skills Module Cards */}
              {isOpen && (
                <div className="p-5 border-t border-slate-800/80 space-y-3 bg-[#09090b]/50">
                  {stage.skills?.map((item: any) => (
                    <div
                      key={item.skillId}
                      className={`p-4 rounded-2xl border transition-all ${
                        item.isCompleted
                          ? 'bg-emerald-950/20 border-emerald-500/30'
                          : 'bg-slate-900/70 border-slate-800 hover:border-slate-700'
                      }`}
                    >
                      <div className="flex items-start justify-between gap-4">
                        <div className="flex items-start gap-3">
                          <button
                            onClick={() => handleToggleSkillComplete(item.skillId, item.isCompleted)}
                            className="mt-0.5 transition-transform hover:scale-110"
                          >
                            {item.isCompleted ? (
                              <CheckCircle2 className="w-5 h-5 text-emerald-400 fill-emerald-400/20" />
                            ) : (
                              <Circle className="w-5 h-5 text-slate-500 hover:text-indigo-400" />
                            )}
                          </button>
                          <div>
                            <div className="flex items-center gap-2">
                              <h4 className={`text-sm font-bold ${item.isCompleted ? 'text-emerald-300 line-through opacity-80' : 'text-white'}`}>
                                {item.name}
                              </h4>
                              <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-slate-800 text-slate-400">
                                {item.category}
                              </span>
                            </div>
                            <p className="text-xs text-slate-400 mt-1">{item.description}</p>
                          </div>
                        </div>

                        <div className="flex items-center gap-3 text-xs font-mono shrink-0">
                          <span className="text-slate-400 flex items-center gap-1">
                            <Clock className="w-3.5 h-3.5 text-slate-500" /> {item.estimatedHours}h
                          </span>
                        </div>
                      </div>

                      {/* Resources preview */}
                      {item.resources?.length > 0 && (
                        <div className="mt-3 pt-3 border-t border-slate-800/60 flex items-center gap-3 text-xs">
                          <span className="text-[10px] font-mono uppercase text-slate-500">Resource Links:</span>
                          <div className="flex flex-wrap gap-2">
                            {item.resources.slice(0, 2).map((res: any, idx: number) => (
                              <a
                                key={idx}
                                href={res.url}
                                target="_blank"
                                rel="noreferrer"
                                className="text-[11px] text-indigo-400 hover:underline flex items-center gap-1"
                              >
                                {res.title} <ExternalLink className="w-3 h-3" />
                              </a>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};
